version: '3'
services:
  vpn:
    image: jeroenslot/nordvpn-proxy:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 103.86.96.100
      - 103.86.99.100
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ovpn-data:/app/ovpn/config
    environment:
      - USERNAME=<nordvpn_username>
      - PASSWORD=<nordvpn_password>
      - LOCAL_NETWORK=192.168.1.0/24
    networks:
      - default
    ports:
      - 8118:8118
    restart: always

volumes:
  ovpn-data: